Repository hacking-papa/nuricame-web, pull requests merged in 2020-04, with the labels that each got.

#10 Install OpenCV
  .gcloudignore
  .github/pull_request_template.md
  .gitignore
  README.md
  app.yaml
  main.py
  requirements.txt
  templates/index.html
  test_main.py
Labels: enhancement

#19 Implement thinning algorithms
  .gcloudignore
  HED.py
  MorphoThinning.py
  ZhangSuen.py
  main.py
  requirements.txt
Labels: enhancement

#12 Install alpine.js and add sample code
  .vscode/settings.json
  README.md
  static/css/base.css
  static/css/bulma-0.8.2/css/bulma-pageloader.min.css
  static/css/bulma-0.8.2/css/bulma-pageloader.sass
  static/img/arrow-down.svg
  static/img/envelope-regular.svg
  static/js/BulmaJS-0.10.3/bulma.js
  static/js/alpine-2.2.5/alpine-ie11.js
  static/js/alpine-2.2.5/alpine.js
  static/js/axios-0.19.2/axios.js
  static/js/axios-0.19.2/axios.map
  static/js/axios-0.19.2/axios.min.js
  static/js/axios-0.19.2/axios.min.map
  static/js/main.js
  templates/base.html
  templates/index.html
  test_MorphoThinning.py
  test_ZhangSuen.py
Labels: enhancement

#28 Change processing on error
  main.py
  static/js/main.js
  templates/base.html
  templates/index.html
Labels: bug

#25 Insert Materials
  app.yaml
  main.py
  static/android-chrome-192x192.png
  static/android-chrome-512x512.png
  static/apple-touch-icon.png
  static/css/base.css
  static/css/bulma-0.8.2/sass/bulma-pageloader.sass
  static/favicon-16x16.png
  static/favicon-32x32.png
  static/favicon.ico
  static/favicon.png
  static/img/01_hackingpapa_logo.png
  static/img/02_logo.png
  static/img/03_take.png
  static/img/04_up.png
  static/img/05_saruphoto.png
  static/img/06_nurieka.png
  static/img/07_nurieflam_4093x2894.png
  static/img/08_products.png
  static/img/09_photo.png
  static/img/10_hackingpapa_logo_2.png
  static/img/OGP.png
  static/js/main.js
  static/manifest.json
  templates/base.html
  templates/index.html
Labels: enhancement

#29 Introduce Google Analytics
  templates/base.html
Labels: enhancement

#30 Compose Frame and Image
  Frame.py
  HED.py
  frame.png
  main.py
  tests/test_Frame.py
Labels: enhancement

#31 Add QR code for PC view
  static/img/qr-code.svg
  templates/index.html
Labels: enhancement

#38 Feat 035 disclaimer
  static/css/base.css
  templates/index.html
Labels: enhancement

#36 Split SPA into Upload and Result
  .vscode/settings.json
  README.md
  main.py
  static/img/03_button2.png
  static/js/axios-0.19.2/axios.js
  static/js/axios-0.19.2/axios.map
  static/js/axios-0.19.2/axios.min.js
  static/js/axios-0.19.2/axios.min.map
  static/js/main.js
  templates/base.html
  templates/index.html
  templates/result.html
Labels: enhancement

#40 Handle Errors
  app.yaml
  error_handlers/default_error.html
  error_handlers/over_quota.html
  error_handlers/timeout.html
  main.py
  static/manifest.json
  templates/base.html
  templates/index.html
Labels: bug, enhancement

#33 Design Feedback
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  main.py
  static/css/base.css
  static/img/03_take.png
  static/img/04_up.png
  static/img/05_saruphoto.png
  static/img/06_nurieka.png
  static/img/07_nurieflam_4093x2894.png
  static/img/08_products.png
  static/img/09_photo.png
  static/img/10_hackingpapa_logo_2.png
  static/img/arrow-down.png
  static/img/arrow-down.svg
  static/img/button_gotoTOP.png
  static/img/button_photoSelect.png
  static/img/child.png
  static/img/envelope-regular.svg
  static/img/hacking-papa_logo.png
  static/img/mail.png
  static/img/monkey_converted.png
  static/img/monkey_original.png
  static/img/nuricame-web_logo.png
  static/img/printer.png
  static/img/products.png
  templates/base.html
  templates/index.html
  templates/result.html
Labels: bug

#32 Update LICENSE.md
  LICENSE.md
  README.md
  static/img/cc-icons-svg/by.svg
  static/img/cc-icons-svg/cc.svg
  static/img/cc-icons-svg/nc-eu.svg
  static/img/cc-icons-svg/nc-jp.svg
  static/img/cc-icons-svg/nc.svg
  static/img/cc-icons-svg/nd.svg
  static/img/cc-icons-svg/pd.svg
  static/img/cc-icons-svg/remix.svg
  static/img/cc-icons-svg/sa.svg
  static/img/cc-icons-svg/sampling.plus.svg
  static/img/cc-icons-svg/sampling.svg
  static/img/cc-icons-svg/share.svg
  static/img/cc-icons-svg/zero.svg
Labels: enhancement

#46 Revise Typographical Error
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/pull_request_template.md
  static/img/button_photoSelect.png
  templates/index.html
Labels: bug

#48 A server error occurs when a session is terminated while /result is still intact
  main.py
Labels: bug
